### ISSUE TITLE
Nodeca throwing error when code is definitely correct....

### ISSUE THREAD

**Issue by mikeerickson** [nodeca/nodeca#31]
I have a simple gulp tasks which is throwing an error

````
import gulp   from 'gulp'
import msg    from 'gulp-messenger'
import run    from 'run-sequence'

msg.init({showPipeFile: false})

gulp.task('build', () => {
  run('clean:dist', 'babelify')
})
````

It is complaining the line where `run` is called is not indented with a single tab, when in fact is definitely is

8:3  warning  Expected indentation of 1 tab character but found 0  indent
8:3  error    Bad indentation (0 instead 1)                        nodeca/indent

So, to help matters, tried disabling the rules for this file but thinking this should still not throw errors

I have retyped this code several times to make sure it is accurate, still throws errors

**Comment by puzrin** [comment]
Are you sure you write to right repo? Here are no any gulp

**Comment by mikeerickson** [comment]
@puzrin I am not saying the actual running of the gulp task is the error, i am saying nodeca/indent is say that specific line is not indented correctly.  When it it clearly is.

I have eslint check all my code and with the exception of this gulp tasks, everything is fine.,

**Comment by puzrin** [comment]
https://github.com/nodeca/eslint-plugin-nodeca
