### ISSUE TITLE
interface / design notes for contest

### ISSUE THREAD

**Issue by puzrin** [nodeca/nodeca#34]
Preparation for 99designs contest

- Current demo link https://dev.rcopen.com/
  - play with it first! don't reinvent abstract forum from scratch.
- Register to see more controls
- Contact vitaly@rcdesign.ru about problems with demo and additional questions

--------------------------

#### Main approach

- [ ] Need usability, not just design with nice puctures.
- [ ] Easy to read big number of posts, for everyday use (more important that "wow" for novices). Don't irritate user attention by splashes and so on.
- [ ] Responsive. Should be ok both on desktop and mobiles (narrow vertical screen)
- [ ] Need some space for unobtrusive ads.

Current demo was done by programmers with those requirements in mind (as they could). Now need rework to become production ready.

_Important_

- That's a complex project, not limited by contest. You should be able to continue after contest compleete - fix usability issues & design more pages.

_Known issues_

- [ ] In long topic - progress bar/buttons not accessible after enter. Until you start scroll down. Can't go to topic end immediately.
- [ ] If too much time passed between posts, "spacer" with text "XXX months later" can be injected between. [Example](http://talk.commonmark.org/t/unicode-character-bullet-u-2022/397/47)
- [ ] Must have quick search access everywhere, with immediate result:
  - search topics in section
  - search posts in thread
  - global search with filters
- [ ] Multiselect (post/topics for moderation) - now shift+click to start, will not work on mobiles. How to improve?
- [ ] Can't access main menu when progress shown (do we really need it?)

----------------------------------

#### Important pages to design:

1. [Forum index](https://dev.rcopen.com/)
2. [Forum section](https://dev.rcopen.com/forum/f91)
3. [Forum topic](https://dev.rcopen.com/forum/f91/topic331689)
4. [User profile](https://dev.rcopen.com/member349)

_Secondary pages:_

5. [Albums-related](https://dev.rcopen.com/member62016/albums)
   - list of albums + list of medias,
   - media page with comments

_Future (not ready now on demo)_

- User blogs
- Clubs
- Direct messages

**Comment by puzrin** [comment]
Contest started

**Comment by 99fella** [comment]
Hi ... Is there any specific colour you are interested as am starting your work now?

Cheers.
Haja (99fella)
https://99designs.co.uk/profiles/99fella

**Comment by puzrin** [comment]
Nothing special about color. All requirements are to UX:

- to be easy to read tons of messages for everyday users
- don't steal attention to secondary elements (for example, you will not see in demo info under user avatars, as many forums have, and so on)

That means, site should be claim/neutral and don't drill user's brain.

If you can reach such goal with bright red - it will be accepted without penalties :)

**Comment by 99fella** [comment]
you wont believe me that I already chosen red / grey / black. And thanks for your quick reply; my version gonna be there soon. 

Ta ;)

**Comment by puzrin** [comment]
The only advice is to study demo "as ordinary user". It has no design, but is balanced in terms of "visual element weights" - all secondary things are minimized, dimmed or hidden. It's a much better start point than most popular forums.

**Comment by 99fella** [comment]
sure, will take your words into account. started your forum index - https://dev.rcopen.com/ page and i hope this is okay to start with.

**Comment by puzrin** [comment]
Update: added requirement (first msg, known ussues):

If too much time passed between posts, "spacer" with text "XXX months later" can be injected between. [Example](http://talk.commonmark.org/t/unicode-character-bullet-u-2022/397/47). That's not implemented in demo yet.

**Comment by puzrin** [comment]
Close - finished.

Results are now published in https://github.com/nodeca/nodeca-design
